name: apply
on:
  push:
    branches: [main]

jobs:
  changed-emails:
    name: changed-emails
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    # Output list of changed email files as a JSON array. This will be used as
    # the input for the matrix for environments to apply.
    outputs:
      emails: ${{ steps.emails.outputs.list }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          list-files: json
          filters: |
            emails: '*.jsonnet'

      # Trim the trailing `.jsonnet` extension from the emails
      - name: Normalize emails
        id: emails
        run: |
          list="$(echo "${STEPS_FILTER_OUTPUTS_EMAILS_FILES}" | jq -rc 'map(sub(".jsonnet$"; ""))')"
          echo "list=${list}" >> "$GITHUB_OUTPUT"
        env:
          STEPS_FILTER_OUTPUTS_EMAILS_FILES: ${{ steps.filter.outputs.emails_files }}

  apply:
    name: apply for ${{ matrix.email }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: changed-emails
    if: ${{ needs.changed-emails.outputs.emails != '[]' }}

    strategy:
      matrix:
        email: ${{ fromJson(needs.changed-emails.outputs.emails) }}

    environment: ${{ matrix.email }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install credentials
        run: |
          mkdir "$HOME/.gmailctl"
          echo "$TOKEN" > "$HOME/.gmailctl/token.json"
          echo "$CREDENTIALS" > "$HOME/.gmailctl/credentials.json"
        env:
          TOKEN: ${{ secrets.GMAIL_TOKEN }}
          CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}

      - name: Update token
        run: gmailctl init --refresh-expired

      - name: Produce filter diff
        run: |
          gmailctl diff -f "${MATRIX_EMAIL}.jsonnet" 2>&1 | tee filters.diff
        env:
          MATRIX_EMAIL: ${{ matrix.email }}

      - name: Read diff output into variable
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: diff
        with:
          script: |
            const fs = require('fs');
            return fs.readFileSync('filters.diff','utf8').toString();
          result-encoding: string

      - name: Create commit comment
        uses: peter-evans/commit-comment@76d2ae14b83cd171cd38507097b9616bb9ca7cb6 # v2.0.1
        with:
          token: ${{ secrets.github_token }}
          body: |
            The following changes are applied to **${{ matrix.email }}** by this commit

            ```diff
            ${{ steps.diff.outputs.result }}
            ```

      - name: Apply changes
        run: gmailctl apply --yes --remove-labels -f "${MATRIX_EMAIL}.jsonnet"
        env:
          MATRIX_EMAIL: ${{ matrix.email }}
