name: apply
on:
  push:
    branches: [main]

jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest
    permissions:
      contents: write

    environment: ${{ matrix.email }}
    strategy:
      matrix:
        email:
          - evanpurkhiser@gmail.com
          - evan.purkhiser@sentry.io

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"

      - name: Install gmailctl
        run: go install github.com/mbrt/gmailctl/cmd/gmailctl@latest

      - name: Install credentials
        run: |
          mkdir "$HOME/.gmailctl"
          echo "$TOKEN" > "$HOME/.gmailctl/token.json"
          echo "$CREDENTIALS" > "$HOME/.gmailctl/credentials.json"
        env:
          TOKEN: ${{ secrets.GMAIL_TOKEN }}
          CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}

      - name: Update token
        run: gmailctl init --refresh-expired

      - name: Produce filter diff
        run: |
          gmailctl diff -f ${{ matrix.email }}.jsonnet 2>&1 | tee filters.diff

      - name: Read diff output into variable
        uses: actions/github-script@v6
        id: diff
        with:
          script: |
            const fs = require('fs');
            return fs.readFileSync('filters.diff','utf8').toString();
          result-encoding: string

      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.github_token }}
          body: |
            The following changes are applied to **${{ matrix.email }}** by this commit

            ```diff
            ${{ steps.diff.outputs.result }}
            ```

      - name: Apply changes
        run: gmailctl apply --yes --remove-labels -f ${{ matrix.email }}.jsonnet
