name: approve
on:
  issues:
    types:
      - labeled

jobs:
  approve:
    if: github.event.label.name == 'Approve'
    name: approve
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Changes approved, [applying filter changes](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})!

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"

      - name: Install gmailctl
        run: go install github.com/mbrt/gmailctl/cmd/gmailctl@latest

      - name: Install credentials
        run: |
          mkdir "$HOME/.gmailctl"
          echo "$TOKEN" > "$HOME/.gmailctl/token.json"
          echo "$CREDENTIALS" > "$HOME/.gmailctl/credentials.json"
        env:
          TOKEN: ${{ secrets.GMAIL_TOKEN }}
          CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}

      - name: Update token
        run: gmailctl init --refresh-expired

      - name: Produce filter diff
        run: gmailctl apply --yes -f evanpurkhiser@gmail.com.jsonnet

      - name: Close applied issue
        uses: lee-dohm/close-matching-issues@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "label:Pending"
